#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("myStockQuote.Resource", IsApplication=true)]

namespace myStockQuote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::myStockQuote.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::myStockQuote.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::myStockQuote.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::myStockQuote.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::myStockQuote.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::myStockQuote.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::myStockQuote.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::myStockQuote.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::myStockQuote.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::myStockQuote.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::myStockQuote.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::myStockQuote.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::myStockQuote.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::myStockQuote.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::myStockQuote.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::myStockQuote.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::myStockQuote.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::myStockQuote.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::myStockQuote.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::myStockQuote.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::myStockQuote.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int HisList = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int HisTitle = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int OptionHostName = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int OptionPort = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int OptionRemoteServer = 2131034120;
			
			// aapt resource value: 0x7f05002a
			public const int OptionsButton = 2131034154;
			
			// aapt resource value: 0x7f05000c
			public const int QuoteDate = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int QuoteDividend = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int QuoteEarnings = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int QuoteMktCap = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int QuoteNet = 2131034133;
			
			// aapt resource value: 0x7f05001a
			public const int QuoteOutstandingShares = 2131034138;
			
			// aapt resource value: 0x7f05000f
			public const int QuotePrice = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int QuoteTitle = 2131034123;
			
			// aapt resource value: 0x7f050025
			public const int ResultFullName = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int ResultMessage = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int ResultResultState = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int ResultStackTrace = 2131034152;
			
			// aapt resource value: 0x7f05001f
			public const int ResultsFailed = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int ResultsId = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int ResultsIgnored = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int ResultsInconclusive = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int ResultsMessage = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int ResultsPassed = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int ResultsResult = 2131034141;
			
			// aapt resource value: 0x7f050029
			public const int RunTestsButton = 2131034153;
			
			// aapt resource value: 0x7f050024
			public const int SearchList = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int SearchMessage = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int TestSuiteListView = 2131034155;
			
			// aapt resource value: 0x7f050005
			public const int btnGetHistory = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int btnGetQuote = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int btnQpageGetHistory = 2131034139;
			
			// aapt resource value: 0x7f050006
			public const int btnSearchStocks = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int myLayout = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int sQuote = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int search = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int space1 = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int space2 = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int tableLayout1 = 2131034125;
			
			// aapt resource value: 0x7f050016
			public const int tableLayout2 = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow1 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int tableRow3 = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int tableRow4 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int tableRow5 = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HistoryPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuotePopUp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int results = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SearchResultsLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int test_result = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int test_suite = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
